// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cloud

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CloudClient is the client API for Cloud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudClient interface {
	Commit(ctx context.Context, in *CloudObject, opts ...grpc.CallOption) (*OperationResult, error)
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (Cloud_SubscribeClient, error)
}

type cloudClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudClient(cc grpc.ClientConnInterface) CloudClient {
	return &cloudClient{cc}
}

func (c *cloudClient) Commit(ctx context.Context, in *CloudObject, opts ...grpc.CallOption) (*OperationResult, error) {
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, "/protos.cloud.Cloud/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (Cloud_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cloud_ServiceDesc.Streams[0], "/protos.cloud.Cloud/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &cloudSubscribeClient{stream}
	return x, nil
}

type Cloud_SubscribeClient interface {
	Send(*CloudObject) error
	Recv() (*CloudObject, error)
	grpc.ClientStream
}

type cloudSubscribeClient struct {
	grpc.ClientStream
}

func (x *cloudSubscribeClient) Send(m *CloudObject) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cloudSubscribeClient) Recv() (*CloudObject, error) {
	m := new(CloudObject)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CloudServer is the server API for Cloud service.
// All implementations must embed UnimplementedCloudServer
// for forward compatibility
type CloudServer interface {
	Commit(context.Context, *CloudObject) (*OperationResult, error)
	Subscribe(Cloud_SubscribeServer) error
	mustEmbedUnimplementedCloudServer()
}

// UnimplementedCloudServer must be embedded to have forward compatible implementations.
type UnimplementedCloudServer struct {
}

func (UnimplementedCloudServer) Commit(context.Context, *CloudObject) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedCloudServer) Subscribe(Cloud_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedCloudServer) mustEmbedUnimplementedCloudServer() {}

// UnsafeCloudServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudServer will
// result in compilation errors.
type UnsafeCloudServer interface {
	mustEmbedUnimplementedCloudServer()
}

func RegisterCloudServer(s grpc.ServiceRegistrar, srv CloudServer) {
	s.RegisterService(&Cloud_ServiceDesc, srv)
}

func _Cloud_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.cloud.Cloud/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServer).Commit(ctx, req.(*CloudObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cloud_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CloudServer).Subscribe(&cloudSubscribeServer{stream})
}

type Cloud_SubscribeServer interface {
	Send(*CloudObject) error
	Recv() (*CloudObject, error)
	grpc.ServerStream
}

type cloudSubscribeServer struct {
	grpc.ServerStream
}

func (x *cloudSubscribeServer) Send(m *CloudObject) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cloudSubscribeServer) Recv() (*CloudObject, error) {
	m := new(CloudObject)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Cloud_ServiceDesc is the grpc.ServiceDesc for Cloud service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cloud_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.cloud.Cloud",
	HandlerType: (*CloudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Commit",
			Handler:    _Cloud_Commit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Cloud_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/cloud/cloud.proto",
}
