nodeId: node-1
logger:
  level: debug
nodeServer:
  port: :40042
server:
  port: :50052
  nodes:
    - localhost:40043
repository:
  type: cassandra
cassandra:
  hosts:
    - localhost
  keyspace: cloud
  templatesRoot: repository/cassandra/queries/templates
client:
  serverAddress: localhost:50052
