version: '3.4'

services:
  app:
    build:
      context: ..
      dockerfile: app/Dockerfile
    hostname: dpc_app
    environment:
      NODE_ENV: dev
    volumes:
      - ../../:/app
    working_dir: /app
    ports:
      - 50051:50051
    command: tail -F anything
    privileged: true
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:3
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./cassandra/cassandra_data:/var/lib/cassandra

  cassandra-load-keyspace:
    image: cassandra:3
    container_name: cassandra-load-keyspace
    depends_on:
      - cassandra
    volumes:
      - ./cassandra/schema.cql:/schema.cql
    command: /bin/bash -c "sleep 30 && echo loading cassandra keyspace && cqlsh cassandra -f ./schema.cql"
